image: node:8
pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - export IMAGE_NAME=ivyowl/alpine-node-pupetteer
          - yarn build:all
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
